---
title: "Chiropractic Clusters"
author: "Byron Dennis"
date: "April 29, 2017"
output:
  word_document: default
  html_document: default
---



```{r Import}

chiro_data<-read.csv("Chiro_Data.csv")

#set row names and remove the name column
rownames(chiro_data) = (chiro_data[,1])
chiro_data <- chiro_data[,-1]

#remove untits, cases, and service Count
chiro_data <- chiro_data[,-3]

chiro_data <- chiro_data[,-3]

chiro_data <- chiro_data[,-3]


summary(chiro_data)


```


#Scale Data
```{r minmax}

normalize<- function(x){return((x-min(x))/(max(x)-min(x)))}
chiro_data_n<-as.data.frame(lapply(chiro_data[,1:15], normalize))
summary(chiro_data_n)

```







```{r hierarchical}

dissimilarity.matrix <- dist(as.matrix(chiro_data_n, method="euclidean"))
chiro_hierarchical<- hclust(dissimilarity.matrix) #default agglomeration method is complete linkage.
plot(chiro_hierarchical, main = "Dendrogam of Chiro utilization", hang = -1) #three or four main clusters


```


#try three clusters
```{r Kmeans 3 clusters}


set.seed(225)
chiro_kmeans3 <- kmeans(chiro_data_n[,1:15], centers = 3)

#add cluster assignment to original data
chiro_data_n$Cluster3 <- chiro_kmeans3$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans3$size

# View Characteristics
t(round(chiro_kmeans3$centers, digits = 2))

#Visualize clusters
library(fpc)
plotcluster(chiro_data_n, chiro_data_n$Cluster3, main="k = 3")




```


#try 4 clusters
```{r kmeans 4 clusters}

set.seed(225)
chiro_kmeans4 <- kmeans(chiro_data_n[,1:15], centers = 4)

#add cluster assignment to original data
chiro_data_n$Cluster4 <- chiro_kmeans4$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans4$size

# View Characteristics
t(round(chiro_kmeans4$centers, digits = 2))

#Visualize clusters
library(fpc)
plotcluster(chiro_data_n, chiro_data_n$Cluster4, main="k = 4")


```


#check betweenness and withinness
```{r separation and cohesion}

#Separation
clusters3_betweenss<- chiro_kmeans3$betweenss/chiro_kmeans3$totss
clusters4_betweenss<- chiro_kmeans4$betweenss/chiro_kmeans4$totss


betweenss.metric <- c(clusters3_betweenss, clusters4_betweenss)
print(betweenss.metric) #Look for a ratio that is closer to 1.


#cohesion
clusters3_withinss<- chiro_kmeans3$tot.withinss/chiro_kmeans3$totss
clusters4_withinss<- chiro_kmeans4$tot.withinss/chiro_kmeans4$totss

totwithinss.metric <- c(clusters3_withinss, clusters4_withinss)
print(totwithinss.metric) #Looking for a ratio that is closer to 0. 

# four clusters seems like the best option.  

```


#try clusters on a subset of unscaled data to assist with interpretation
```{r kmeans3 reduced data}


#create dataframe with which only inlucdes unit counts for different service types
chiro_data_reduced<-chiro_data[,7:15]


dissimilarity.matrix_reduced <- dist(as.matrix(chiro_data_reduced, method="euclidean"))
chiro_hierarchical_reduced<- hclust(dissimilarity.matrix_reduced) #default agglomeration method is complete linkage.
plot(chiro_hierarchical_reduced, main = "Dendrogam of Chiro utilization", hang = -1) # Looks like 4-5 clusters now




set.seed(225)
chiro_kmeans3_red <- kmeans(chiro_data_reduced[1:9], centers = 3)

#add cluster assignment to original data
chiro_data_reduced$Cluster3_red <- chiro_kmeans3_red$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans3_red$size

# View Characteristics
clusters_3_red <- data.frame(t(round(chiro_kmeans3_red$centers, digits = 2)))
clusters_3_red[order(-clusters_3_red$X3), ] 

#Visualize clusters
library(fpc)
plotcluster(chiro_data_reduced[1:9], chiro_data_reduced$Cluster3, main="k = 3")



```


#try clusters on a subset of unscaled data again but with 4 clusters
```{r kmeans4 reduced data}


set.seed(225)
chiro_kmeans4_red <- kmeans(chiro_data_reduced[1:9], centers = 4)

#add cluster assignment to original data
chiro_data_reduced$Cluster4_red <- chiro_kmeans4_red$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans4_red$size

# View Characteristics
clusters_4_red <- data.frame(t(round(chiro_kmeans4_red$centers, digits = 2)))
clusters_4_red[order(-clusters_4_red$X3), ] 

#Visualize clusters
library(fpc)
plotcluster(chiro_data_reduced[1:9], chiro_data_reduced$Cluster4, main="k = 4")



```



#Check Separation and Cohesion Again

```{r separation and cohesion v2}

#Separation
clusters3_betweenss_red<- chiro_kmeans3_red$betweenss/chiro_kmeans3_red$totss
clusters4_betweenss_red<- chiro_kmeans4_red$betweenss/chiro_kmeans4_red$totss


betweenss.metric_red <- c(clusters3_betweenss_red, clusters4_betweenss_red)
print(betweenss.metric_red) #Look for a ratio that is closer to 1.


#cohesion
clusters3_withinss_red<- chiro_kmeans3_red$tot.withinss/chiro_kmeans3_red$totss
clusters4_withinss_red<- chiro_kmeans4_red$tot.withinss/chiro_kmeans4_red$totss

totwithinss.metric_red <- c(clusters3_withinss_red, clusters4_withinss_red)
print(totwithinss.metric_red) #Looking for a ratio that is closer to 0. 

```




#trying 5 clusters
```{r kmeans5 reduced data}


set.seed(225)
chiro_kmeans5_red <- kmeans(chiro_data_reduced[1:9], centers = 5)

#add cluster assignment to original data
chiro_data_reduced$Cluster5_red <- chiro_kmeans5_red$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans5_red$size

# View Characteristics
clusters_5_red <- data.frame(t(round(chiro_kmeans5_red$centers, digits = 2)))
clusters_5_red[order(-clusters_5_red$X3), ] 

#Visualize clusters
library(fpc)
plotcluster(chiro_data_reduced[1:9], chiro_data_reduced$Cluster5, main="k = 5")



```


# what about 6 clusters?

```{r kmeans6 reduced data}


set.seed(225)
chiro_kmeans6_red <- kmeans(chiro_data_reduced[1:9], centers = 6)

#add cluster assignment to original data
chiro_data_reduced$Cluster6_red <- chiro_kmeans6_red$cluster

#see how many chiro groups are assigned to each cluster
chiro_kmeans6_red$size

# View Characteristics
clusters_6_red <- data.frame(t(round(chiro_kmeans6_red$centers, digits = 2)))
clusters_6_red[order(-clusters_6_red$X3), ] 

#Visualize clusters
library(fpc)
plotcluster(chiro_data_reduced[1:9], chiro_data_reduced$Cluster6, main="k = 6")



```






#Check Separation and Cohesion Final...going to exclude 6 clusters

```{r separation and cohesion v3}

#Separation
clusters3_betweenss_red<- chiro_kmeans3_red$betweenss/chiro_kmeans3_red$totss
clusters4_betweenss_red<- chiro_kmeans4_red$betweenss/chiro_kmeans4_red$totss
clusters5_betweenss_red<- chiro_kmeans5_red$betweenss/chiro_kmeans5_red$totss

betweenss.metric_red <- c(clusters3_betweenss_red, clusters4_betweenss_red, clusters5_betweenss_red)
print(betweenss.metric_red) #Look for a ratio that is closer to 1.


#cohesion
clusters3_withinss_red<- chiro_kmeans3_red$tot.withinss/chiro_kmeans3_red$totss
clusters4_withinss_red<- chiro_kmeans4_red$tot.withinss/chiro_kmeans4_red$totss
clusters5_withinss_red<- chiro_kmeans5_red$tot.withinss/chiro_kmeans5_red$totss

totwithinss.metric_red <- c(clusters3_withinss_red, clusters4_withinss_red, clusters5_withinss_red)
print(totwithinss.metric_red) #Looking for a ratio that is closer to 0. 

```


